// utils/countries.js
const countries = [
  {
    code: "EARTH",
    name: {
      en: "Planet Earth",
      uk: "Планета Земля",
      es: "Planeta Tierra",
      fr: "Planète Terre",
      de: "Planet Erde",
      zh: "地球",
      hi: "पृथ्वी ग्रह",
      ar: "كوكب الأرض",
      pt: "Planeta Terra",
      ru: "Планета Земля",
      ja: "地球",
    },
  },
  {
    code: "AF",
    name: {
      en: "Afghanistan",
      uk: "Афганістан",
      es: "Afganistán",
      fr: "Afghanistan",
      de: "Afghanistan",
      zh: "阿富汗",
      hi: "अफ़गानिस्तान",
      ar: "أفغانستان",
      pt: "Afeganistão",
      ru: "Афганистан",
      ja: "アフガニスタン",
    },
  },
  {
    code: "AL",
    name: {
      en: "Albania",
      uk: "Албанія",
      es: "Albania",
      fr: "Albanie",
      de: "Albanien",
      zh: "阿尔巴尼亚",
      hi: "अल्बानिया",
      ar: "ألبانيا",
      pt: "Albânia",
      ru: "Албания",
      ja: "アルバニア",
    },
  },
  {
    code: "DZ",
    name: {
      en: "Algeria",
      uk: "Алжир",
      es: "Argelia",
      fr: "Algérie",
      de: "Algerien",
      zh: "阿尔及利亚",
      hi: "अल्जीरिया",
      ar: "الجزائر",
      pt: "Argélia",
      ru: "Алжир",
      ja: "アルジェリア",
    },
  },
  {
    code: "AD",
    name: {
      en: "Andorra",
      uk: "Андорра",
      es: "Andorra",
      fr: "Andorre",
      de: "Andorra",
      zh: "安道尔",
      hi: "अंडोरा",
      ar: "أندورا",
      pt: "Andorra",
      ru: "Андорра",
      ja: "アンドラ",
    },
  },
  {
    code: "AO",
    name: {
      en: "Angola",
      uk: "Ангола",
      es: "Angola",
      fr: "Angola",
      de: "Angola",
      zh: "安哥拉",
      hi: "अंगोला",
      ar: "أنغولا",
      pt: "Angola",
      ru: "Ангола",
      ja: "アンゴラ",
    },
  },
  {
    code: "AR",
    name: {
      en: "Argentina",
      uk: "Аргентина",
      es: "Argentina",
      fr: "Argentine",
      de: "Argentinien",
      zh: "阿根廷",
      hi: "अर्जेंटीना",
      ar: "الأرجنتين",
      pt: "Argentina",
      ru: "Аргентина",
      ja: "アルゼンチン",
    },
  },
  {
    code: "AM",
    name: {
      en: "Armenia",
      uk: "Вірменія",
      es: "Armenia",
      fr: "Arménie",
      de: "Armenien",
      zh: "亚美尼亚",
      hi: "आर्मेनिया",
      ar: "أرمينيا",
      pt: "Armênia",
      ru: "Армения",
      ja: "アルメニア",
    },
  },
  {
    code: "AU",
    name: {
      en: "Australia",
      uk: "Австралія",
      es: "Australia",
      fr: "Australie",
      de: "Australien",
      zh: "澳大利亚",
      hi: "ऑस्ट्रेलिया",
      ar: "أستراليا",
      pt: "Austrália",
      ru: "Австралия",
      ja: "オーストラリア",
    },
  },
  {
    code: "AT",
    name: {
      en: "Austria",
      uk: "Австрія",
      es: "Austria",
      fr: "Autriche",
      de: "Österreich",
      zh: "奥地利",
      hi: "ऑस्ट्रिया",
      ar: "النمسا",
      pt: "Áustria",
      ru: "Австрия",
      ja: "オーストリア",
    },
  },
  {
    code: "AZ",
    name: {
      en: "Azerbaijan",
      uk: "Азербайджан",
      es: "Azerbaiyán",
      fr: "Azerbaïdjan",
      de: "Aserbaidschan",
      zh: "阿塞拜疆",
      hi: "अज़रबैजान",
      ar: "أذربيجان",
      pt: "Azerbaijão",
      ru: "Азербайджан",
      ja: "アゼルバイジャン",
    },
  },
  {
    code: "BS",
    name: {
      en: "Bahamas",
      uk: "Багамські Острови",
      es: "Bahamas",
      fr: "Bahamas",
      de: "Bahamas",
      zh: "巴哈马",
      hi: "बहामास",
      ar: "البهاما",
      pt: "Bahamas",
      ru: "Багамские Острова",
      ja: "バハマ",
    },
  },
  {
    code: "BH",
    name: {
      en: "Bahrain",
      uk: "Бахрейн",
      es: "Baréin",
      fr: "Bahreïn",
      de: "Bahrain",
      zh: "巴林",
      hi: "बहरीन",
      ar: "البحرين",
      pt: "Bahrein",
      ru: "Бахрейн",
      ja: "バーレーン",
    },
  },
  {
    code: "BD",
    name: {
      en: "Bangladesh",
      uk: "Бангладеш",
      es: "Bangladés",
      fr: "Bangladesh",
      de: "Bangladesch",
      zh: "孟加拉国",
      hi: "बांग्लादेश",
      ar: "بنغلاديش",
      pt: "Bangladesh",
      ru: "Бангладеш",
      ja: "バングラデシュ",
    },
  },
  {
    code: "BB",
    name: {
      en: "Barbados",
      uk: "Барбадос",
      es: "Barbados",
      fr: "Barbade",
      de: "Barbados",
      zh: "巴巴多斯",
      hi: "बारबाडोस",
      ar: "باربادوس",
      pt: "Barbados",
      ru: "Барбадос",
      ja: "バルバドス",
    },
  },
  {
    code: "BY",
    name: {
      en: "Belarus",
      uk: "Білорусь",
      es: "Bielorrusia",
      fr: "Biélorussie",
      de: "Weißrussland",
      zh: "白俄罗斯",
      hi: "बेलारूस",
      ar: "بيلاروس",
      pt: "Bielorrússia",
      ru: "Беларусь",
      ja: "ベラルーシ",
    },
  },
  {
    code: "BE",
    name: {
      en: "Belgium",
      uk: "Бельгія",
      es: "Bélgica",
      fr: "Belgique",
      de: "Belgien",
      zh: "比利时",
      hi: "बेल्जियम",
      ar: "بلجيكا",
      pt: "Bélgica",
      ru: "Бельгия",
      ja: "ベルギー",
    },
  },
  {
    code: "BZ",
    name: {
      en: "Belize",
      uk: "Беліз",
      es: "Belice",
      fr: "Belize",
      de: "Belize",
      zh: "伯利兹",
      hi: "बेलीज़",
      ar: "بليز",
      pt: "Belize",
      ru: "Белиз",
      ja: "ベリーズ",
    },
  },
  {
    code: "BJ",
    name: {
      en: "Benin",
      uk: "Бенін",
      es: "Benín",
      fr: "Bénin",
      de: "Benin",
      zh: "贝宁",
      hi: "बेनिन",
      ar: "بنين",
      pt: "Benin",
      ru: "Бенин",
      ja: "ベナン",
    },
  },
  {
    code: "BT",
    name: {
      en: "Bhutan",
      uk: "Бутан",
      es: "Bután",
      fr: "Bhoutan",
      de: "Bhutan",
      zh: "不丹",
      hi: "भूटान",
      ar: "بوتان",
      pt: "Butão",
      ru: "Бутан",
      ja: "ブータン",
    },
  },
  {
    code: "BO",
    name: {
      en: "Bolivia",
      uk: "Болівія",
      es: "Bolivia",
      fr: "Bolivie",
      de: "Bolivien",
      zh: "玻利维亚",
      hi: "बोलीविया",
      ar: "بوليفيا",
      pt: "Bolívia",
      ru: "Боливия",
      ja: "ボリビア",
    },
  },
  {
    code: "BA",
    name: {
      en: "Bosnia and Herzegovina",
      uk: "Боснія і Герцеговина",
      es: "Bosnia y Herzegovina",
      fr: "Bosnie-Herzégovine",
      de: "Bosnien und Herzegowina",
      zh: "波斯尼亚和黑塞哥维那",
      hi: "बोस्निया और हर्ज़ेगोविना",
      ar: "البوسنة والهرسك",
      pt: "Bósnia e Herzegovina",
      ru: "Босния и Герцеговина",
      ja: "ボスニア・ヘルツェゴビナ",
    },
  },
  {
    code: "BW",
    name: {
      en: "Botswana",
      uk: "Ботсвана",
      es: "Botsuana",
      fr: "Botswana",
      de: "Botswana",
      zh: "博茨瓦纳",
      hi: "बोत्सवाना",
      ar: "بوتسوانا",
      pt: "Botsuana",
      ru: "Ботсвана",
      ja: "ボツワナ",
    },
  },
  {
    code: "BR",
    name: {
      en: "Brazil",
      uk: "Бразилія",
      es: "Brasil",
      fr: "Brésil",
      de: "Brasilien",
      zh: "巴西",
      hi: "ब्राज़ील",
      ar: "البرازيل",
      pt: "Brasil",
      ru: "Бразилия",
      ja: "ブラジル",
    },
  },
  {
    code: "BN",
    name: {
      en: "Brunei",
      uk: "Бруней",
      es: "Brunéi",
      fr: "Brunei",
      de: "Brunei",
      zh: "文莱",
      hi: "ब्रुनेई",
      ar: "بروناي",
      pt: "Brunei",
      ru: "Бруней",
      ja: "ブルネイ",
    },
  },
  {
    code: "BG",
    name: {
      en: "Bulgaria",
      uk: "Болгарія",
      es: "Bulgaria",
      fr: "Bulgarie",
      de: "Bulgarien",
      zh: "保加利亚",
      hi: "बुल्गारिया",
      ar: "بلغاريا",
      pt: "Bulgária",
      ru: "Болгария",
      ja: "ブルガリア",
    },
  },
  {
    code: "BF",
    name: {
      en: "Burkina Faso",
      uk: "Буркіна-Фасо",
      es: "Burkina Faso",
      fr: "Burkina Faso",
      de: "Burkina Faso",
      zh: "布基纳法索",
      hi: "बुर्किना फ़ासो",
      ar: "بوركينا فاسو",
      pt: "Burkina Faso",
      ru: "Буркина-Фасо",
      ja: "ブルキナファソ",
    },
  },
  {
    code: "BI",
    name: {
      en: "Burundi",
      uk: "Бурунді",
      es: "Burundi",
      fr: "Burundi",
      de: "Burundi",
      zh: "布隆迪",
      hi: "बुस्र्न्दी",
      ar: "بوروندي",
      pt: "Burundi",
      ru: "Бурунди",
      ja: "ブルンジ",
    },
  },
  {
    code: "CV",
    name: {
      en: "Cabo Verde",
      uk: "Кабо-Верде",
      es: "Cabo Verde",
      fr: "Cap-Vert",
      de: "Kap Verde",
      zh: "佛得角",
      hi: "केप वर्डे",
      ar: "الرأس الأخضر",
      pt: "Cabo Verde",
      ru: "Кабо-Верде",
      ja: "カーボベルデ",
    },
  },
  {
    code: "KH",
    name: {
      en: "Cambodia",
      uk: "Камбоджа",
      es: "Camboya",
      fr: "Cambodge",
      de: "Kambodscha",
      zh: "柬埔寨",
      hi: "कंबोडिया",
      ar: "كمبوديا",
      pt: "Camboja",
      ru: "Камбоджа",
      ja: "カンボジア",
    },
  },
  {
    code: "CM",
    name: {
      en: "Cameroon",
      uk: "Камерун",
      es: "Camerún",
      fr: "Cameroun",
      de: "Kamerun",
      zh: "喀麦隆",
      hi: "कैमरून",
      ar: "الكاميرون",
      pt: "Camarões",
      ru: "Камерун",
      ja: "カメルーン",
    },
  },
  {
    code: "CA",
    name: {
      en: "Canada",
      uk: "Канада",
      es: "Canadá",
      fr: "Canada",
      de: "Kanada",
      zh: "加拿大",
      hi: "कनाडा",
      ar: "كندا",
      pt: "Canadá",
      ru: "Канада",
      ja: "カナダ",
    },
  },
  {
    code: "CF",
    name: {
      en: "Central African Republic",
      uk: "Центральноафриканська Республіка",
      es: "República Centroafricana",
      fr: "République centrafricaine",
      de: "Zentralafrikanische Republik",
      zh: "中非共和国",
      hi: "मध्य अफ़्रीकी गणराज्य",
      ar: "جمهورية أفريقيا الوسطى",
      pt: "República Centro-Africana",
      ru: "Центральноафриканская Республика",
      ja: "中央アフリカ共和国",
    },
  },
  {
    code: "TD",
    name: {
      en: "Chad",
      uk: "Чад",
      es: "Chad",
      fr: "Tchad",
      de: "Tschad",
      zh: "乍得",
      hi: "चाड",
      ar: "تشاد",
      pt: "Chade",
      ru: "Чад",
      ja: "チャド",
    },
  },
  {
    code: "CL",
    name: {
      en: "Chile",
      uk: "Чилі",
      es: "Chile",
      fr: "Chili",
      de: "Chile",
      zh: "智利",
      hi: "चिली",
      ar: "تشيلي",
      pt: "Chile",
      ru: "Чили",
      ja: "チリ",
    },
  },
  {
    code: "CN",
    name: {
      en: "China",
      uk: "Китай",
      es: "China",
      fr: "Chine",
      de: "China",
      zh: "中国",
      hi: "चीन",
      ar: "الصين",
      pt: "China",
      ru: "Китай",
      ja: "中国",
    },
  },
  {
    code: "CO",
    name: {
      en: "Colombia",
      uk: "Колумбія",
      es: "Colombia",
      fr: "Colombie",
      de: "Kolumbien",
      zh: "哥伦比亚",
      hi: "कोलंबिया",
      ar: "كولومبيا",
      pt: "Colômbia",
      ru: "Колумбия",
      ja: "コロンビア",
    },
  },
  {
    code: "KM",
    name: {
      en: "Comoros",
      uk: "Коморські Острови",
      es: "Comoras",
      fr: "Comores",
      de: "Komoren",
      zh: "科摩罗",
      hi: "कोमोरोस",
      ar: "جزر القمر",
      pt: "Comores",
      ru: "Коморы",
      ja: "コモロ",
    },
  },
  {
    code: "CG",
    name: {
      en: "Congo",
      uk: "Конго",
      es: "Congo",
      fr: "Congo",
      de: "Kongo",
      zh: "刚果",
      hi: "कांगो",
      ar: "الكونغو",
      pt: "Congo",
      ru: "Конго",
      ja: "コンゴ",
    },
  },
  {
    code: "CR",
    name: {
      en: "Costa Rica",
      uk: "Коста-Рика",
      es: "Costa Rica",
      fr: "Costa Rica",
      de: "Costa Rica",
      zh: "哥斯达黎加",
      hi: "कोस्टा रिका",
      ar: "كوستاريكا",
      pt: "Costa Rica",
      ru: "Коста-Рика",
      ja: "コスタリカ",
    },
  },
  {
    code: "HR",
    name: {
      en: "Croatia",
      uk: "Хорватія",
      es: "Croacia",
      fr: "Croatie",
      de: "Kroatien",
      zh: "克罗地亚",
      hi: "क्रोएशिया",
      ar: "كرواتيا",
      pt: "Croácia",
      ru: "Хорватия",
      ja: "クロアチア",
    },
  },
  {
    code: "CU",
    name: {
      en: "Cuba",
      uk: "Куба",
      es: "Cuba",
      fr: "Cuba",
      de: "Kuba",
      zh: "古巴",
      hi: "क्यूबा",
      ar: "كوبا",
      pt: "Cuba",
      ru: "Куба",
      ja: "キューバ",
    },
  },
  {
    code: "CY",
    name: {
      en: "Cyprus",
      uk: "Кіпр",
      es: "Chipre",
      fr: "Chypre",
      de: "Zypern",
      zh: "塞浦路斯",
      hi: "साइप्रस",
      ar: "قبرص",
      pt: "Chipre",
      ru: "Кипр",
      ja: "キプロス",
    },
  },
  {
    code: "CZ",
    name: {
      en: "Czech Republic",
      uk: "Чехія",
      es: "República Checa",
      fr: "République tchèque",
      de: "Tschechien",
      zh: "捷克共和国",
      hi: "चेक गणराज्य",
      ar: "التشيك",
      pt: "República Checa",
      ru: "Чехия",
      ja: "チェコ",
    },
  },
  {
    code: "DK",
    name: {
      en: "Denmark",
      uk: "Данія",
      es: "Dinamarca",
      fr: "Danemark",
      de: "Dänemark",
      zh: "丹麦",
      hi: "डेनमार्क",
      ar: "الدنمارك",
      pt: "Dinamarca",
      ru: "Дания",
      ja: "デンマーク",
    },
  },
  {
    code: "DJ",
    name: {
      en: "Djibouti",
      uk: "Джибуті",
      es: "Yibuti",
      fr: "Djibouti",
      de: "Dschibuti",
      zh: "吉布提",
      hi: "जिबूती",
      ar: "جيبوتي",
      pt: "Djibuti",
      ru: "Джибути",
      ja: "ジブチ",
    },
  },
  {
    code: "DM",
    name: {
      en: "Dominica",
      uk: "Домініка",
      es: "Dominica",
      fr: "Dominique",
      de: "Dominica",
      zh: "多米尼克",
      hi: "डोमिनिका",
      ar: "دومينيكا",
      pt: "Dominica",
      ru: "Доминика",
      ja: "ドミニカ",
    },
  },
  {
    code: "DO",
    name: {
      en: "Dominican Republic",
      uk: "Домініканська Республіка",
      es: "República Dominicana",
      fr: "République dominicaine",
      de: "Dominikanische Republik",
      zh: "多米尼加共和国",
      hi: "डोमिनिकन गणराज्य",
      ar: "جمهورية الدومينيكان",
      pt: "República Dominicana",
      ru: "Доминиканская Республика",
      ja: "ドミニカ共和国",
    },
  },
  {
    code: "EC",
    name: {
      en: "Ecuador",
      uk: "Еквадор",
      es: "Ecuador",
      fr: "Équateur",
      de: "Ecuador",
      zh: "厄瓜多尔",
      hi: "इक्वाडोर",
      ar: "الإكوادور",
      pt: "Equador",
      ru: "Эквадор",
      ja: "エクアドル",
    },
  },
  {
    code: "EG",
    name: {
      en: "Egypt",
      uk: "Єгипет",
      es: "Egipto",
      fr: "Égypte",
      de: "Ägypten",
      zh: "埃及",
      hi: "मिस्र",
      ar: "مصر",
      pt: "Egito",
      ru: "Египет",
      ja: "エジプト",
    },
  },
  {
    code: "SV",
    name: {
      en: "El Salvador",
      uk: "Сальвадор",
      es: "El Salvador",
      fr: "Salvador",
      de: "El Salvador",
      zh: "萨尔瓦多",
      hi: "अल सल्वाडोर",
      ar: "السلفادور",
      pt: "El Salvador",
      ru: "Сальвадор",
      ja: "エルサルバドル",
    },
  },
  {
    code: "GQ",
    name: {
      en: "Equatorial Guinea",
      uk: "Екваторіальна Гвінея",
      es: "Guinea Ecuatorial",
      fr: "Guinée équatoriale",
      de: "Äquatorialguinea",
      zh: "赤道几内亚",
      hi: "इक्वेटोरियल गिनी",
      ar: "غينيا الاستوائية",
      pt: "Guiné Equatorial",
      ru: "Экваториальная Гвинея",
      ja: "赤道ギニア",
    },
  },
  {
    code: "ER",
    name: {
      en: "Eritrea",
      uk: "Еритрея",
      es: "Eritrea",
      fr: "Érythrée",
      de: "Eritrea",
      zh: "厄立特里亚",
      hi: "इरिट्रिया",
      ar: "إريتريا",
      pt: "Eritreia",
      ru: "Эритрея",
      ja: "エリトリア",
    },
  },
  {
    code: "EE",
    name: {
      en: "Estonia",
      uk: "Естонія",
      es: "Estonia",
      fr: "Estonie",
      de: "Estland",
      zh: "爱沙尼亚",
      hi: "एस्टोनिया",
      ar: "إستونيا",
      pt: "Estônia",
      ru: "Эстония",
      ja: "エストニア",
    },
  },
  {
    code: "SZ",
    name: {
      en: "Eswatini",
      uk: "Есватіні",
      es: "Esuatini",
      fr: "Eswatini",
      de: "Eswatini",
      zh: "斯威士兰",
      hi: "एस्वाटीनी",
      ar: "إسواتيني",
      pt: "Essuatíni",
      ru: "Эсватини",
      ja: "エスワティニ",
    },
  },
  {
    code: "ET",
    name: {
      en: "Ethiopia",
      uk: "Ефіопія",
      es: "Etiopía",
      fr: "Éthiopie",
      de: "Äthiopien",
      zh: "埃塞俄比亚",
      hi: "इथियोपिया",
      ar: "إثيوبيا",
      pt: "Etiópia",
      ru: "Эфиопия",
      ja: "エチオピア",
    },
  },
  {
    code: "FJ",
    name: {
      en: "Fiji",
      uk: "Фіджі",
      es: "Fiyi",
      fr: "Fidji",
      de: "Fidschi",
      zh: "斐济",
      hi: "फ़िजी",
      ar: "فيجي",
      pt: "Fiji",
      ru: "Фиджи",
      ja: "フィジー",
    },
  },
  {
    code: "FI",
    name: {
      en: "Finland",
      uk: "Фінляндія",
      es: "Finlandia",
      fr: "Finlande",
      de: "Finnland",
      zh: "芬兰",
      hi: "फ़िनलैंड",
      ar: "فنلندا",
      pt: "Finlândia",
      ru: "Финляндия",
      ja: "フィンランド",
    },
  },
  {
    code: "FR",
    name: {
      en: "France",
      uk: "Франція",
      es: "Francia",
      fr: "France",
      de: "Frankreich",
      zh: "法国",
      hi: "फ़्रांस",
      ar: "فرنسا",
      pt: "França",
      ru: "Франция",
      ja: "フランス",
    },
  },
  {
    code: "GA",
    name: {
      en: "Gabon",
      uk: "Габон",
      es: "Gabón",
      fr: "Gabon",
      de: "Gabun",
      zh: "加蓬",
      hi: "गैबॉन",
      ar: "الغابون",
      pt: "Gabão",
      ru: "Габон",
      ja: "ガボン",
    },
  },
  {
    code: "GM",
    name: {
      en: "Gambia",
      uk: "Гамбія",
      es: "Gambia",
      fr: "Gambie",
      de: "Gambia",
      zh: "冈比亚",
      hi: "गाम्बिया",
      ar: "غامبيا",
      pt: "Gâmbia",
      ru: "Гамбия",
      ja: "ガンビア",
    },
  },
  {
    code: "GE",
    name: {
      en: "Georgia",
      uk: "Грузія",
      es: "Georgia",
      fr: "Géorgie",
      de: "Georgien",
      zh: "格鲁吉亚",
      hi: "जॉर्जिया",
      ar: "جورجيا",
      pt: "Geórgia",
      ru: "Грузия",
      ja: "ジョージア",
    },
  },
  {
    code: "DE",
    name: {
      en: "Germany",
      uk: "Німеччина",
      es: "Alemania",
      fr: "Allemagne",
      de: "Deutschland",
      zh: "德国",
      hi: "जर्मनी",
      ar: "ألمانيا",
      pt: "Alemanha",
      ru: "Германия",
      ja: "ドイツ",
    },
  },
  {
    code: "GH",
    name: {
      en: "Ghana",
      uk: "Гана",
      es: "Ghana",
      fr: "Ghana",
      de: "Ghana",
      zh: "加纳",
      hi: "घाना",
      ar: "غانا",
      pt: "Gana",
      ru: "Гана",
      ja: "ガーナ",
    },
  },
  {
    code: "GR",
    name: {
      en: "Greece",
      uk: "Греція",
      es: "Grecia",
      fr: "Grèce",
      de: "Griechenland",
      zh: "希腊",
      hi: "यूनान",
      ar: "اليونان",
      pt: "Grécia",
      ru: "Греция",
      ja: "ギリシャ",
    },
  },
  {
    code: "GD",
    name: {
      en: "Grenada",
      uk: "Гренада",
      es: "Granada",
      fr: "Grenade",
      de: "Grenada",
      zh: "格林纳达",
      hi: "ग्रेनाडा",
      ar: "غرينادا",
      pt: "Granada",
      ru: "Гренада",
      ja: "グレナダ",
    },
  },
  {
    code: "GT",
    name: {
      en: "Guatemala",
      uk: "Гватемала",
      es: "Guatemala",
      fr: "Guatemala",
      de: "Guatemala",
      zh: "危地马拉",
      hi: "ग्वाटेमाला",
      ar: "غواتيمالا",
      pt: "Guatemala",
      ru: "Гватемала",
      ja: "グアテマラ",
    },
  },
  {
    code: "GN",
    name: {
      en: "Guinea",
      uk: "Гвінея",
      es: "Guinea",
      fr: "Guinée",
      de: "Guinea",
      zh: "几内亚",
      hi: "गिनी",
      ar: "غينيا",
      pt: "Guiné",
      ru: "Гвинея",
      ja: "ギニア",
    },
  },
  {
    code: "GW",
    name: {
      en: "Guinea-Bissau",
      uk: "Гвінея-Бісау",
      es: "Guinea-Bisáu",
      fr: "Guinée-Bissau",
      de: "Guinea-Bissau",
      zh: "几内亚比绍",
      hi: "गिनी-बिसाऊ",
      ar: "غينيا بيساو",
      pt: "Guiné-Bissau",
      ru: "Гвинея-Бисау",
      ja: "ギニアビサウ",
    },
  },
  {
    code: "GY",
    name: {
      en: "Guyana",
      uk: "Гаяна",
      es: "Guyana",
      fr: "Guyana",
      de: "Guyana",
      zh: "圭亚那",
      hi: "गुयाना",
      ar: "غيانا",
      pt: "Guiana",
      ru: "Гайана",
      ja: "ガイアナ",
    },
  },
  {
    code: "HT",
    name: {
      en: "Haiti",
      uk: "Гаїті",
      es: "Haití",
      fr: "Haïti",
      de: "Haiti",
      zh: "海地",
      hi: "हाइती",
      ar: "هايتي",
      pt: "Haiti",
      ru: "Гаити",
      ja: "ハイチ",
    },
  },
  {
    code: "HN",
    name: {
      en: "Honduras",
      uk: "Гондурас",
      es: "Honduras",
      fr: "Honduras",
      de: "Honduras",
      zh: "洪都拉斯",
      hi: "होंडुरास",
      ar: "هندوراس",
      pt: "Honduras",
      ru: "Гондурас",
      ja: "ホンジュラス",
    },
  },
  {
    code: "HU",
    name: {
      en: "Hungary",
      uk: "Угорщина",
      es: "Hungría",
      fr: "Hongrie",
      de: "Ungarn",
      zh: "匈牙利",
      hi: "हंगरी",
      ar: "المجر",
      pt: "Hungria",
      ru: "Венгрия",
      ja: "ハンガリー",
    },
  },
  {
    code: "IS",
    name: {
      en: "Iceland",
      uk: "Ісландія",
      es: "Islandia",
      fr: "Islande",
      de: "Island",
      zh: "冰岛",
      hi: "आइसलैंड",
      ar: "آيسلندا",
      pt: "Islândia",
      ru: "Исландия",
      ja: "アイスランド",
    },
  },
  {
    code: "IN",
    name: {
      en: "India",
      uk: "Індія",
      es: "India",
      fr: "Inde",
      de: "Indien",
      zh: "印度",
      hi: "भारत",
      ar: "الهند",
      pt: "Índia",
      ru: "Индия",
      ja: "インド",
    },
  },
  {
    code: "ID",
    name: {
      en: "Indonesia",
      uk: "Індонезія",
      es: "Indonesia",
      fr: "Indonésie",
      de: "Indonesien",
      zh: "印度尼西亚",
      hi: "इंडोनेशिया",
      ar: "إندونيسيا",
      pt: "Indonésia",
      ru: "Индонезия",
      ja: "インドネシア",
    },
  },
  {
    code: "IR",
    name: {
      en: "Iran",
      uk: "Іран",
      es: "Irán",
      fr: "Iran",
      de: "Iran",
      zh: "伊朗",
      hi: "ईरान",
      ar: "إيران",
      pt: "Irã",
      ru: "Иран",
      ja: "イラン",
    },
  },
  {
    code: "IQ",
    name: {
      en: "Iraq",
      uk: "Ірак",
      es: "Irak",
      fr: "Irak",
      de: "Irak",
      zh: "伊拉克",
      hi: "इराक",
      ar: "العراق",
      pt: "Iraque",
      ru: "Ирак",
      ja: "イラク",
    },
  },
  {
    code: "IE",
    name: {
      en: "Ireland",
      uk: "Ірландія",
      es: "Irlanda",
      fr: "Irlande",
      de: "Irland",
      zh: "爱尔兰",
      hi: "आयरलैंड",
      ar: "أيرلندا",
      pt: "Irlanda",
      ru: "Ирландия",
      ja: "アイルランド",
    },
  },
  {
    code: "IL",
    name: {
      en: "Israel",
      uk: "Ізраїль",
      es: "Israel",
      fr: "Israël",
      de: "Israel",
      zh: "以色列",
      hi: "इजराइल",
      ar: "إسرائيل",
      pt: "Israel",
      ru: "Израиль",
      ja: "イスラエル",
    },
  },
  {
    code: "IT",
    name: {
      en: "Italy",
      uk: "Італія",
      es: "Italia",
      fr: "Italie",
      de: "Italien",
      zh: "意大利",
      hi: "इटली",
      ar: "إيطاليا",
      pt: "Itália",
      ru: "Италия",
      ja: "イタリア",
    },
  },
  {
    code: "JM",
    name: {
      en: "Jamaica",
      uk: "Ямайка",
      es: "Jamaica",
      fr: "Jamaïque",
      de: "Jamaika",
      zh: "牙买加",
      hi: "जमैका",
      ar: "جامايكا",
      pt: "Jamaica",
      ru: "Ямайка",
      ja: "ジャマイカ",
    },
  },
  {
    code: "JP",
    name: {
      en: "Japan",
      uk: "Японія",
      es: "Japón",
      fr: "Japon",
      de: "Japan",
      zh: "日本",
      hi: "जापान",
      ar: "اليابان",
      pt: "Japão",
      ru: "Япония",
      ja: "日本",
    },
  },
  {
    code: "JO",
    name: {
      en: "Jordan",
      uk: "Йорданія",
      es: "Jordania",
      fr: "Jordanie",
      de: "Jordanien",
      zh: "约旦",
      hi: "जॉर्डन",
      ar: "الأردن",
      pt: "Jordânia",
      ru: "Иордания",
      ja: "ヨルダン",
    },
  },
  {
    code: "KZ",
    name: {
      en: "Kazakhstan",
      uk: "Казахстан",
      es: "Kazajistán",
      fr: "Kazakhstan",
      de: "Kasachstan",
      zh: "哈萨克斯坦",
      hi: "कज़ाखस्तान",
      ar: "كازاخستان",
      pt: "Cazaquistão",
      ru: "Казахстан",
      ja: "カザフスタン",
    },
  },
  {
    code: "KE",
    name: {
      en: "Kenya",
      uk: "Кенія",
      es: "Kenia",
      fr: "Kenya",
      de: "Kenia",
      zh: "肯尼亚",
      hi: "केन्या",
      ar: "كينيا",
      pt: "Quênia",
      ru: "Кения",
      ja: "ケニア",
    },
  },
  {
    code: "KI",
    name: {
      en: "Kiribati",
      uk: "Кірибаті",
      es: "Kiribati",
      fr: "Kiribati",
      de: "Kiribati",
      zh: "基里巴斯",
      hi: "किरिबाती",
      ar: "كيريباتي",
      pt: "Kiribati",
      ru: "Кирибати",
      ja: "キリバス",
    },
  },
  {
    code: "KP",
    name: {
      en: "North Korea",
      uk: "Північна Корея",
      es: "Corea del Norte",
      fr: "Corée du Nord",
      de: "Nordkorea",
      zh: "朝鲜",
      hi: "उत्तर कोरिया",
      ar: "كوريا الشمالية",
      pt: "Coreia do Norte",
      ru: "КНДР",
      ja: "北朝鮮",
    },
  },
  {
    code: "KR",
    name: {
      en: "South Korea",
      uk: "Південна Корея",
      es: "Corea del Sur",
      fr: "Corée du Sud",
      de: "Südkorea",
      zh: "韩国",
      hi: "दक्षिण कोरिया",
      ar: "كوريا الجنوبية",
      pt: "Coreia do Sul",
      ru: "Южная Корея",
      ja: "韓国",
    },
  },
  {
    code: "KW",
    name: {
      en: "Kuwait",
      uk: "Кувейт",
      es: "Kuwait",
      fr: "Koweït",
      de: "Kuwait",
      zh: "科威特",
      hi: "कुवैत",
      ar: "الكويت",
      pt: "Kuwait",
      ru: "Кувейт",
      ja: "クウェート",
    },
  },
  {
    code: "KG",
    name: {
      en: "Kyrgyzstan",
      uk: "Киргизстан",
      es: "Kirguistán",
      fr: "Kirghizistan",
      de: "Kirgisistan",
      zh: "吉尔吉斯斯坦",
      hi: "किर्गिज़स्तान",
      ar: "قيرغيزستان",
      pt: "Quirguistão",
      ru: "Кыргызстан",
      ja: "キルギス",
    },
  },
  {
    code: "LA",
    name: {
      en: "Laos",
      uk: "Лаос",
      es: "Laos",
      fr: "Laos",
      de: "Laos",
      zh: "老挝",
      hi: "लाओस",
      ar: "لاوس",
      pt: "Laos",
      ru: "Лаос",
      ja: "ラオス",
    },
  },
  {
    code: "LV",
    name: {
      en: "Latvia",
      uk: "Латвія",
      es: "Letonia",
      fr: "Lettonie",
      de: "Lettland",
      zh: "拉脱维亚",
      hi: "लातविया",
      ar: "لاتفيا",
      pt: "Letônia",
      ru: "Латвия",
      ja: "ラトビア",
    },
  },
  {
    code: "LB",
    name: {
      en: "Lebanon",
      uk: "Ліван",
      es: "Líbano",
      fr: "Liban",
      de: "Libanon",
      zh: "黎巴嫩",
      hi: "लेबनान",
      ar: "لبنان",
      pt: "Líbano",
      ru: "Ливан",
      ja: "レバノン",
    },
  },
  {
    code: "LS",
    name: {
      en: "Lesotho",
      uk: "Лесото",
      es: "Lesoto",
      fr: "Lesotho",
      de: "Lesotho",
      zh: "莱索托",
      hi: "लेसोथो",
      ar: "ليسوتو",
      pt: "Lesoto",
      ru: "Лесото",
      ja: "レソト",
    },
  },
  {
    code: "LR",
    name: {
      en: "Liberia",
      uk: "Ліберія",
      es: "Liberia",
      fr: "Libéria",
      de: "Liberia",
      zh: "利比里亚",
      hi: "लाइबेरिया",
      ar: "ليبيريا",
      pt: "Libéria",
      ru: "Либерия",
      ja: "リベリア",
    },
  },
  {
    code: "LY",
    name: {
      en: "Libya",
      uk: "Лівія",
      es: "Libia",
      fr: "Libye",
      de: "Libyen",
      zh: "利比亚",
      hi: "लीबिया",
      ar: "ليبيا",
      pt: "Líbia",
      ru: "Ливия",
      ja: "リビア",
    },
  },
  {
    code: "LI",
    name: {
      en: "Liechtenstein",
      uk: "Ліхтенштейн",
      es: "Liechtenstein",
      fr: "Liechtenstein",
      de: "Liechtenstein",
      zh: "列支敦士登",
      hi: "लिचेंस्टीन",
      ar: "ليختنشتاين",
      pt: "Liechtenstein",
      ru: "Лихтенштейн",
      ja: "リヒテンシュタイン",
    },
  },
  {
    code: "LT",
    name: {
      en: "Lithuania",
      uk: "Литва",
      es: "Lituania",
      fr: "Lituanie",
      de: "Litauen",
      zh: "立陶宛",
      hi: "लिथुआनिया",
      ar: "ليتوانيا",
      pt: "Lituânia",
      ru: "Литва",
      ja: "リトアニア",
    },
  },
  {
    code: "LU",
    name: {
      en: "Luxembourg",
      uk: "Люксембург",
      es: "Luxemburgo",
      fr: "Luxembourg",
      de: "Luxemburg",
      zh: "卢森堡",
      hi: "लक्ज़मबर्ग",
      ar: "لوكسمبورغ",
      pt: "Luxemburgo",
      ru: "Люксембург",
      ja: "ルクセンブルク",
    },
  },
  {
    code: "MG",
    name: {
      en: "Madagascar",
      uk: "Мадагаскар",
      es: "Madagascar",
      fr: "Madagascar",
      de: "Madagaskar",
      zh: "马达加斯加",
      hi: "मडागास्कर",
      ar: "مدغشقر",
      pt: "Madagáscar",
      ru: "Мадагаскар",
      ja: "マダガスカル",
    },
  },
  {
    code: "MW",
    name: {
      en: "Malawi",
      uk: "Малаві",
      es: "Malaui",
      fr: "Malawi",
      de: "Malawi",
      zh: "马拉维",
      hi: "मलावी",
      ar: "مالاوي",
      pt: "Malawi",
      ru: "Малави",
      ja: "マラウイ",
    },
  },
  {
    code: "MY",
    name: {
      en: "Malaysia",
      uk: "Малайзія",
      es: "Malasia",
      fr: "Malaisie",
      de: "Malaysia",
      zh: "马来西亚",
      hi: "मलेशिया",
      ar: "ماليزيا",
      pt: "Malásia",
      ru: "Малайзия",
      ja: "マレーシア",
    },
  },
  {
    code: "MV",
    name: {
      en: "Maldives",
      uk: "Мальдіви",
      es: "Maldivas",
      fr: "Maldives",
      de: "Malediven",
      zh: "马尔代夫",
      hi: "मालदीव",
      ar: "المالديف",
      pt: "Maldivas",
      ru: "Мальдивы",
      ja: "モルディブ",
    },
  },
  {
    code: "ML",
    name: {
      en: "Mali",
      uk: "Малі",
      es: "Mali",
      fr: "Mali",
      de: "Mali",
      zh: "马里",
      hi: "माली",
      ar: "مالي",
      pt: "Mali",
      ru: "Мали",
      ja: "マリ",
    },
  },
  {
    code: "MT",
    name: {
      en: "Malta",
      uk: "Мальта",
      es: "Malta",
      fr: "Malte",
      de: "Malta",
      zh: "马耳他",
      hi: "माल्टा",
      ar: "مالطا",
      pt: "Malta",
      ru: "Мальта",
      ja: "マルタ",
    },
  },
  {
    code: "MH",
    name: {
      en: "Marshall Islands",
      uk: "Маршаллові Острови",
      es: "Islas Marshall",
      fr: "Îles Marshall",
      de: "Marshallinseln",
      zh: "马绍尔群岛",
      hi: "मार्शल द्वीप",
      ar: "جزر مارشال",
      pt: "Ilhas Marshall",
      ru: "Маршалловы Острова",
      ja: "マーシャル諸島",
    },
  },
  {
    code: "MR",
    name: {
      en: "Mauritania",
      uk: "Мавританія",
      es: "Mauritania",
      fr: "Mauritanie",
      de: "Mauretanien",
      zh: "毛里塔尼亚",
      hi: "मॉरिटानिया",
      ar: "موريتانيا",
      pt: "Mauritânia",
      ru: "Мавритания",
      ja: "モーリタニア",
    },
  },
  {
    code: "MU",
    name: {
      en: "Mauritius",
      uk: "Маврикій",
      es: "Mauricio",
      fr: "Maurice",
      de: "Mauritius",
      zh: "毛里求斯",
      hi: "मॉरीशस",
      ar: "موريشيوس",
      pt: "Maurício",
      ru: "Маврикий",
      ja: "モーリシャス",
    },
  },
  {
    code: "MX",
    name: {
      en: "Mexico",
      uk: "Мексика",
      es: "México",
      fr: "Mexique",
      de: "Mexiko",
      zh: "墨西哥",
      hi: "मेक्सिको",
      ar: "المكسيك",
      pt: "México",
      ru: "Мексика",
      ja: "メキシコ",
    },
  },
  {
    code: "FM",
    name: {
      en: "Micronesia",
      uk: "Мікронезія",
      es: "Micronesia",
      fr: "Micronésie",
      de: "Mikronesien",
      zh: "密克罗尼西亚",
      hi: "माइक्रोनेशिया",
      ar: "ولايات ميكرونيسيا المتحدة",
      pt: "Micronésia",
      ru: "Микронезия",
      ja: "ミクロネシア",
    },
  },
  {
    code: "MD",
    name: {
      en: "Moldova",
      uk: "Молдова",
      es: "Moldavia",
      fr: "Moldavie",
      de: "Moldawien",
      zh: "摩尔多瓦",
      hi: "मॉल्डोवा",
      ar: "مولدوفا",
      pt: "Moldávia",
      ru: "Молдова",
      ja: "モルドバ",
    },
  },
  {
    code: "MC",
    name: {
      en: "Monaco",
      uk: "Монако",
      es: "Mónaco",
      fr: "Monaco",
      de: "Monaco",
      zh: "摩纳哥",
      hi: "मोनाको",
      ar: "موناكو",
      pt: "Mônaco",
      ru: "Монако",
      ja: "モナコ",
    },
  },
  {
    code: "MN",
    name: {
      en: "Mongolia",
      uk: "Монголія",
      es: "Mongolia",
      fr: "Mongolie",
      de: "Mongolei",
      zh: "蒙古",
      hi: "मंगोलिया",
      ar: "منغوليا",
      pt: "Mongólia",
      ru: "Монголия",
      ja: "モンゴル",
    },
  },
  {
    code: "ME",
    name: {
      en: "Montenegro",
      uk: "Чорногорія",
      es: "Montenegro",
      fr: "Monténégro",
      de: "Montenegro",
      zh: "黑山",
      hi: "मोंटेनेग्रो",
      ar: "الجبل الأسود",
      pt: "Montenegro",
      ru: "Черногория",
      ja: "モンテネグロ",
    },
  },
  {
    code: "MA",
    name: {
      en: "Morocco",
      uk: "Марокко",
      es: "Marruecos",
      fr: "Maroc",
      de: "Marokko",
      zh: "摩洛哥",
      hi: "मोरक्को",
      ar: "المغرب",
      pt: "Marrocos",
      ru: "Марокко",
      ja: "モロッコ",
    },
  },
  {
    code: "MZ",
    name: {
      en: "Mozambique",
      uk: "Мозамбік",
      es: "Mozambique",
      fr: "Mozambique",
      de: "Mosambik",
      zh: "莫桑比克",
      hi: "मोज़ाम्बिक",
      ar: "موزمبيق",
      pt: "Moçambique",
      ru: "Мозамбик",
      ja: "モザンビーク",
    },
  },
  {
    code: "MM",
    name: {
      en: "Myanmar",
      uk: "М'янма",
      es: "Myanmar",
      fr: "Birmanie",
      de: "Myanmar",
      zh: "缅甸",
      hi: "म्यांमार",
      ar: "ميانمار",
      pt: "Mianmar",
      ru: "Мьянма",
      ja: "ミャンマー",
    },
  },
  {
    code: "NA",
    name: {
      en: "Namibia",
      uk: "Намібія",
      es: "Namibia",
      fr: "Namibie",
      de: "Namibia",
      zh: "纳米比亚",
      hi: "नामीबिया",
      ar: "ناميبيا",
      pt: "Namíbia",
      ru: "Намибия",
      ja: "ナミビア",
    },
  },
  {
    code: "NR",
    name: {
      en: "Nauru",
      uk: "Науру",
      es: "Nauru",
      fr: "Nauru",
      de: "Nauru",
      zh: "瑙鲁",
      hi: "नाउरू",
      ar: "ناورو",
      pt: "Nauru",
      ru: "Науру",
      ja: "ナウル",
    },
  },
  {
    code: "NP",
    name: {
      en: "Nepal",
      uk: "Непал",
      es: "Nepal",
      fr: "Népal",
      de: "Nepal",
      zh: "尼泊尔",
      hi: "नेपाल",
      ar: "نيبال",
      pt: "Nepal",
      ru: "Непал",
      ja: "ネパール",
    },
  },
  {
    code: "NL",
    name: {
      en: "Netherlands",
      uk: "Нідерланди",
      es: "Países Bajos",
      fr: "Pays-Bas",
      de: "Niederlande",
      zh: "荷兰",
      hi: "नीदरलैंड",
      ar: "هولندا",
      pt: "Países Baixos",
      ru: "Нидерланды",
      ja: "オランダ",
    },
  },
  {
    code: "NZ",
    name: {
      en: "New Zealand",
      uk: "Нова Зеландія",
      es: "Nueva Zelanda",
      fr: "Nouvelle-Zélande",
      de: "Neuseeland",
      zh: "新西兰",
      hi: "न्यूज़ीलैंड",
      ar: "نيوزيلندا",
      pt: "Nova Zelândia",
      ru: "Новая Зеландия",
      ja: "ニュージーランド",
    },
  },
  {
    code: "NI",
    name: {
      en: "Nicaragua",
      uk: "Нікарагуа",
      es: "Nicaragua",
      fr: "Nicaragua",
      de: "Nicaragua",
      zh: "尼加拉瓜",
      hi: "निकारागुआ",
      ar: "نيكاراغوا",
      pt: "Nicarágua",
      ru: "Никарагуа",
      ja: "ニカラグア",
    },
  },
  {
    code: "NE",
    name: {
      en: "Niger",
      uk: "Нігер",
      es: "Níger",
      fr: "Niger",
      de: "Niger",
      zh: "尼日尔",
      hi: "नाइजर",
      ar: "النيجر",
      pt: "Níger",
      ru: "Нигер",
      ja: "ニジェール",
    },
  },
  {
    code: "NG",
    name: {
      en: "Nigeria",
      uk: "Нігерія",
      es: "Nigeria",
      fr: "Nigeria",
      de: "Nigeria",
      zh: "尼日利亚",
      hi: "नाइजीरिया",
      ar: "نيجيريا",
      pt: "Nigéria",
      ru: "Нигерия",
      ja: "ナイジェリア",
    },
  },
  {
    code: "NO",
    name: {
      en: "Norway",
      uk: "Норвегія",
      es: "Noruega",
      fr: "Norvège",
      de: "Norwegen",
      zh: "挪威",
      hi: "नॉर्वे",
      ar: "النرويج",
      pt: "Noruega",
      ru: "Норвегия",
      ja: "ノルウェー",
    },
  },
  {
    code: "OM",
    name: {
      en: "Oman",
      uk: "Оман",
      es: "Omán",
      fr: "Oman",
      de: "Oman",
      zh: "阿曼",
      hi: "ओमान",
      ar: "عُمان",
      pt: "Omã",
      ru: "Оман",
      ja: "オマーン",
    },
  },
  {
    code: "PK",
    name: {
      en: "Pakistan",
      uk: "Пакистан",
      es: "Pakistán",
      fr: "Pakistan",
      de: "Pakistan",
      zh: "巴基斯坦",
      hi: "पाकिस्तान",
      ar: "باكستان",
      pt: "Paquistão",
      ru: "Пакистан",
      ja: "パキスタン",
    },
  },
  {
    code: "PW",
    name: {
      en: "Palau",
      uk: "Палау",
      es: "Palaos",
      fr: "Palaos",
      de: "Palau",
      zh: "帕劳",
      hi: "पलाऊ",
      ar: "بالاو",
      pt: "Palau",
      ru: "Палау",
      ja: "パラオ",
    },
  },
  {
    code: "PA",
    name: {
      en: "Panama",
      uk: "Панама",
      es: "Panamá",
      fr: "Panama",
      de: "Panama",
      zh: "巴拿马",
      hi: "पनामा",
      ar: "بنما",
      pt: "Panamá",
      ru: "Панама",
      ja: "パナマ",
    },
  },
  {
    code: "PG",
    name: {
      en: "Papua New Guinea",
      uk: "Папуа-Нова Гвінея",
      es: "Papúa Nueva Guinea",
      fr: "Papouasie-Nouvelle-Guinée",
      de: "Papua-Neuguinea",
      zh: "巴布亚新几内亚",
      hi: "पापुआ न्यू गिनी",
      ar: "بابوا غينيا الجديدة",
      pt: "Papua-Nova Guiné",
      ru: "Папуа — Новая Гвинея",
      ja: "パプアニューギニア",
    },
  },
  {
    code: "PY",
    name: {
      en: "Paraguay",
      uk: "Парагвай",
      es: "Paraguay",
      fr: "Paraguay",
      de: "Paraguay",
      zh: "巴拉圭",
      hi: "पैराग्वे",
      ar: "باراغواي",
      pt: "Paraguai",
      ru: "Парагвай",
      ja: "パラグアイ",
    },
  },
  {
    code: "PE",
    name: {
      en: "Peru",
      uk: "Перу",
      es: "Perú",
      fr: "Péru",
      de: "Peru",
      zh: "秘鲁",
      hi: "पेरू",
      ar: "بيرو",
      pt: "Peru",
      ru: "Перу",
      ja: "ペルー",
    },
  },
  {
    code: "PH",
    name: {
      en: "Philippines",
      uk: "Філіппіни",
      es: "Filipinas",
      fr: "Philippines",
      de: "Philippinen",
      zh: "菲律宾",
      hi: "फ़िलीपींस",
      ar: "الفلبين",
      pt: "Filipinas",
      ru: "Филиппины",
      ja: "フィリピン",
    },
  },
  {
    code: "PL",
    name: {
      en: "Poland",
      uk: "Польща",
      es: "Polonia",
      fr: "Pologne",
      de: "Polen",
      zh: "波兰",
      hi: "पोलैंड",
      ar: "بولندا",
      pt: "Polônia",
      ru: "Польша",
      ja: "ポーランド",
    },
  },
  {
    code: "PT",
    name: {
      en: "Portugal",
      uk: "Португалія",
      es: "Portugal",
      fr: "Portugal",
      de: "Portugal",
      zh: "葡萄牙",
      hi: "पुर्तगाल",
      ar: "البرتغال",
      pt: "Portugal",
      ru: "Португалия",
      ja: "ポルトガル",
    },
  },
  {
    code: "QA",
    name: {
      en: "Qatar",
      uk: "Катар",
      es: "Catar",
      fr: "Qatar",
      de: "Katar",
      zh: "卡塔尔",
      hi: "क़तर",
      ar: "قطر",
      pt: "Catar",
      ru: "Катар",
      ja: "カタール",
    },
  },
  {
    code: "RO",
    name: {
      en: "Romania",
      uk: "Румунія",
      es: "Rumania",
      fr: "Roumanie",
      de: "Rumänien",
      zh: "罗马尼亚",
      hi: "रोमानिया",
      ar: "رومانيا",
      pt: "Romênia",
      ru: "Румыния",
      ja: "ルーマニア",
    },
  },
  {
    code: "RU",
    name: {
      en: "Russia",
      uk: "Росія",
      es: "Rusia",
      fr: "Russie",
      de: "Russland",
      zh: "俄罗斯",
      hi: "रूस",
      ar: "روسيا",
      pt: "Rússia",
      ru: "Россия",
      ja: "ロシア",
    },
  },
  {
    code: "RW",
    name: {
      en: "Rwanda",
      uk: "Руанда",
      es: "Ruanda",
      fr: "Rwanda",
      de: "Ruanda",
      zh: "卢旺达",
      hi: "रवांडा",
      ar: "رواندا",
      pt: "Ruanda",
      ru: "Руанда",
      ja: "ルワンダ",
    },
  },
  {
    code: "KN",
    name: {
      en: "Saint Kitts and Nevis",
      uk: "Сент-Кіттс і Невіс",
      es: "San Cristóbal y Nieves",
      fr: "Saint-Christophe-et-Niévès",
      de: "St. Kitts und Nevis",
      zh: "圣基茨和尼维斯",
      hi: "सेंट किट्स और नेविस",
      ar: "سانت كيتس ونيفيس",
      pt: "São Cristóvão e Neves",
      ru: "Сент-Китс и Невис",
      ja: "セントクリストファー・ネイビス",
    },
  },
  {
    code: "LC",
    name: {
      en: "Saint Lucia",
      uk: "Сент-Люсія",
      es: "Santa Lucía",
      fr: "Sainte-Lucie",
      de: "St. Lucia",
      zh: "圣卢西亚",
      hi: "सेंट लूसिया",
      ar: "سانت لوسيا",
      pt: "Santa Lúcia",
      ru: "Сент-Люсия",
      ja: "セントルシア",
    },
  },
  {
    code: "VC",
    name: {
      en: "Saint Vincent and the Grenadines",
      uk: "Сент-Вінсент і Гренадини",
      es: "San Vicente y las Granadinas",
      fr: "Saint-Vincent-et-les-Grenadines",
      de: "St. Vincent und die Grenadinen",
      zh: "圣文森特和格林纳丁斯",
      hi: "सेंट विंसेंट और ग्रेनाडाइन्स",
      ar: "سانت فينسنت والغرينادين",
      pt: "São Vicente e Granadinas",
      ru: "Сент-Винсент и Гренадины",
      ja: "セントビンセント・グレナディーン",
    },
  },
  {
    code: "WS",
    name: {
      en: "Samoa",
      uk: "Самоа",
      es: "Samoa",
      fr: "Samoa",
      de: "Samoa",
      zh: "萨摩亚",
      hi: "समोआ",
      ar: "ساموا",
      pt: "Samoa",
      ru: "Самоа",
      ja: "サモア",
    },
  },
  {
    code: "SM",
    name: {
      en: "San Marino",
      uk: "Сан-Марино",
      es: "San Marino",
      fr: "Saint-Marin",
      de: "San Marino",
      zh: "圣马力诺",
      hi: "सैन मैरिनो",
      ar: "سان مارينو",
      pt: "San Marino",
      ru: "Сан-Марино",
      ja: "サンマリノ",
    },
  },
  {
    code: "ST",
    name: {
      en: "Sao Tome and Principe",
      uk: "Сан-Томе і Принсіпі",
      es: "Santo Tomé y Príncipe",
      fr: "Sao Tomé-et-Principe",
      de: "São Tomé und Príncipe",
      zh: "圣多美和普林西比",
      hi: "साओ टोम और प्रिंसिपे",
      ar: "ساو تومي وبرينسيب",
      pt: "São Tomé e Príncipe",
      ru: "Сан-Томе и Принсипи",
      ja: "サントメ・プリンシペ",
    },
  },
  {
    code: "SA",
    name: {
      en: "Saudi Arabia",
      uk: "Саудівська Аравія",
      es: "Arabia Saudita",
      fr: "Arabie saoudite",
      de: "Saudi-Arabien",
      zh: "沙特阿拉伯",
      hi: "सऊदी अरब",
      ar: "السعودية",
      pt: "Arábia Saudita",
      ru: "Саудовская Аравия",
      ja: "サウジアラビア",
    },
  },
  {
    code: "SN",
    name: {
      en: "Senegal",
      uk: "Сенегал",
      es: "Senegal",
      fr: "Sénégal",
      de: "Senegal",
      zh: "塞内加尔",
      hi: "सेनेगल",
      ar: "السنغال",
      pt: "Senegal",
      ru: "Сенегал",
      ja: "セネガル",
    },
  },
  {
    code: "RS",
    name: {
      en: "Serbia",
      uk: "Сербія",
      es: "Serbia",
      fr: "Serbie",
      de: "Serbien",
      zh: "塞尔维亚",
      hi: "सर्बिया",
      ar: "صربيا",
      pt: "Sérvia",
      ru: "Сербия",
      ja: "セルビア",
    },
  },
  {
    code: "SC",
    name: {
      en: "Seychelles",
      uk: "Сейшельські Острови",
      es: "Seychelles",
      fr: "Seychelles",
      de: "Seychellen",
      zh: "塞舌尔",
      hi: "सेशेल्स",
      ar: "سيشل",
      pt: "Seicheles",
      ru: "Сейшельские Острова",
      ja: "セーシェル",
    },
  },
  {
    code: "SL",
    name: {
      en: "Sierra Leone",
      uk: "Сьєрра-Леоне",
      es: "Sierra Leona",
      fr: "Sierra Leone",
      de: "Sierra Leone",
      zh: "塞拉利昂",
      hi: "सियरा लिओन",
      ar: "سيراليون",
      pt: "Serra Leoa",
      ru: "Сьерра-Леоне",
      ja: "シエラレオネ",
    },
  },
  {
    code: "SG",
    name: {
      en: "Singapore",
      uk: "Сінгапур",
      es: "Singapur",
      fr: "Singapour",
      de: "Singapur",
      zh: "新加坡",
      hi: "सिंगापुर",
      ar: "سنغافورة",
      pt: "Singapura",
      ru: "Сингапур",
      ja: "シンガポール",
    },
  },
  {
    code: "SK",
    name: {
      en: "Slovakia",
      uk: "Словаччина",
      es: "Eslovaquia",
      fr: "Slovaquie",
      de: "Slowakei",
      zh: "斯洛伐克",
      hi: "स्लोवाकिया",
      ar: "سلوفاكيا",
      pt: "Eslováquia",
      ru: "Словакия",
      ja: "スロバキア",
    },
  },
  {
    code: "SI",
    name: {
      en: "Slovenia",
      uk: "Словенія",
      es: "Eslovenia",
      fr: "Slovénie",
      de: "Slowenien",
      zh: "斯洛文尼亚",
      hi: "स्लोवेनिया",
      ar: "سلوفينيا",
      pt: "Eslovênia",
      ru: "Словения",
      ja: "スロベニア",
    },
  },
  {
    code: "SB",
    name: {
      en: "Solomon Islands",
      uk: "Соломонові Острови",
      es: "Islas Salomón",
      fr: "Îles Salomon",
      de: "Salomonen",
      zh: "所罗门群岛",
      hi: "सोलोमन द्वीप",
      ar: "جزر سليمان",
      pt: "Ilhas Salomão",
      ru: "Соломоновы Острова",
      ja: "ソロモン諸島",
    },
  },
  {
    code: "SO",
    name: {
      en: "Somalia",
      uk: "Сомалі",
      es: "Somalia",
      fr: "Somalie",
      de: "Somalia",
      zh: "索马里",
      hi: "सोमालिया",
      ar: "الصومال",
      pt: "Somália",
      ru: "Сомали",
      ja: "ソマリア",
    },
  },
  {
    code: "ZA",
    name: {
      en: "South Africa",
      uk: "Південна Африка",
      es: "Sudáfrica",
      fr: "Afrique du Sud",
      de: "Südafrika",
      zh: "南非",
      hi: "दक्षिण अफ़्रीका",
      ar: "جنوب أفريقيا",
      pt: "África do Sul",
      ru: "ЮАР",
      ja: "南アフリカ",
    },
  },
  {
    code: "SS",
    name: {
      en: "South Sudan",
      uk: "Південний Судан",
      es: "Sudán del Sur",
      fr: "Soudan du Sud",
      de: "Südsudan",
      zh: "南苏丹",
      hi: "दक्षिण सूडान",
      ar: "جنوب السودان",
      pt: "Sudão do Sul",
      ru: "Южный Судан",
      ja: "南スーダン",
    },
  },
  {
    code: "ES",
    name: {
      en: "Spain",
      uk: "Іспанія",
      es: "España",
      fr: "Espagne",
      de: "Spanien",
      zh: "西班牙",
      hi: "स्पेन",
      ar: "إسبانيا",
      pt: "Espanha",
      ru: "Испания",
      ja: "スペイン",
    },
  },
  {
    code: "LK",
    name: {
      en: "Sri Lanka",
      uk: "Шрі-Ланка",
      es: "Sri Lanka",
      fr: "Sri Lanka",
      de: "Sri Lanka",
      zh: "斯里兰卡",
      hi: "श्रीलंका",
      ar: "سريلانكا",
      pt: "Sri Lanka",
      ru: "Шри-Ланка",
      ja: "スリランカ",
    },
  },
  {
    code: "SD",
    name: {
      en: "Sudan",
      uk: "Судан",
      es: "Sudán",
      fr: "Soudan",
      de: "Sudan",
      zh: "苏丹",
      hi: "सूडान",
      ar: "السودان",
      pt: "Sudão",
      ru: "Судан",
      ja: "スーダン",
    },
  },
  {
    code: "SR",
    name: {
      en: "Suriname",
      uk: "Суринам",
      es: "Surinam",
      fr: "Suriname",
      de: "Suriname",
      zh: "苏里南",
      hi: "सूरीनाम",
      ar: "سورينام",
      pt: "Suriname",
      ru: "Суринам",
      ja: "スリナム",
    },
  },
  {
    code: "SE",
    name: {
      en: "Sweden",
      uk: "Швеція",
      es: "Suecia",
      fr: "Suède",
      de: "Schweden",
      zh: "瑞典",
      hi: "स्वीडन",
      ar: "السويد",
      pt: "Suécia",
      ru: "Швеция",
      ja: "スウェーデン",
    },
  },
  {
    code: "CH",
    name: {
      en: "Switzerland",
      uk: "Швейцарія",
      es: "Suiza",
      fr: "Suisse",
      de: "Schweiz",
      zh: "瑞士",
      hi: "स्विट्जरलैंड",
      ar: "سويسرا",
      pt: "Suíça",
      ru: "Швейцария",
      ja: "スイス",
    },
  },
  {
    code: "SY",
    name: {
      en: "Syria",
      uk: "Сирія",
      es: "Siria",
      fr: "Syrie",
      de: "Syrien",
      zh: "叙利亚",
      hi: "सीरिया",
      ar: "سوريا",
      pt: "Síria",
      ru: "Сирия",
      ja: "シリア",
    },
  },
  {
    code: "TJ",
    name: {
      en: "Tajikistan",
      uk: "Таджикистан",
      es: "Tayikistán",
      fr: "Tadjikistan",
      de: "Tadschikistan",
      zh: "塔吉克斯坦",
      hi: "ताजिकिस्तान",
      ar: "طاجيكستان",
      pt: "Tajiquistão",
      ru: "Таджикистан",
      ja: "タジキスタン",
    },
  },
  {
    code: "TZ",
    name: {
      en: "Tanzania",
      uk: "Танзанія",
      es: "Tanzania",
      fr: "Tanzanie",
      de: "Tansania",
      zh: "坦桑尼亚",
      hi: "तंज़ानिया",
      ar: "تنزانيا",
      pt: "Tanzânia",
      ru: "Танзания",
      ja: "タンザニア",
    },
  },
  {
    code: "TH",
    name: {
      en: "Thailand",
      uk: "Таїланд",
      es: "Tailandia",
      fr: "Thaïlande",
      de: "Thailand",
      zh: "泰国",
      hi: "थाईलैंड",
      ar: "تايلاند",
      pt: "Tailândia",
      ru: "Таиланд",
      ja: "タイ",
    },
  },
  {
    code: "TL",
    name: {
      en: "Timor-Leste",
      uk: "Тимор-Лешті",
      es: "Timor Oriental",
      fr: "Timor oriental",
      de: "Osttimor",
      zh: "东帝汶",
      hi: "तिमोर-लेस्ते",
      ar: "تيمور الشرقية",
      pt: "Timor-Leste",
      ru: "Восточный Тимор",
      ja: "東ティモール",
    },
  },
  {
    code: "TG",
    name: {
      en: "Togo",
      uk: "Того",
      es: "Togo",
      fr: "Togo",
      de: "Togo",
      zh: "多哥",
      hi: "टोगो",
      ar: "توغو",
      pt: "Togo",
      ru: "Того",
      ja: "トーゴ",
    },
  },
  {
    code: "TO",
    name: {
      en: "Tonga",
      uk: "Тонга",
      es: "Tonga",
      fr: "Tonga",
      de: "Tonga",
      zh: "汤加",
      hi: "टोंगा",
      ar: "تونغا",
      pt: "Tonga",
      ru: "Тонга",
      ja: "トンガ",
    },
  },
  {
    code: "TT",
    name: {
      en: "Trinidad and Tobago",
      uk: "Тринідад і Тобаго",
      es: "Trinidad y Tobago",
      fr: "Trinité-et-Tobago",
      de: "Trinidad und Tobago",
      zh: "特立尼达和多巴哥",
      hi: "त्रिनिदाद और टोबैगो",
      ar: "ترينيداد وتوباغو",
      pt: "Trinidad e Tobago",
      ru: "Тринидад и Тобаго",
      ja: "トリニダード・トバゴ",
    },
  },
  {
    code: "TN",
    name: {
      en: "Tunisia",
      uk: "Туніс",
      es: "Túnez",
      fr: "Tunisie",
      de: "Tunesien",
      zh: "突尼斯",
      hi: "ट्यूनीशिया",
      ar: "تونس",
      pt: "Tunísia",
      ru: "Тунис",
      ja: "チュニジア",
    },
  },
  {
    code: "TR",
    name: {
      en: "Turkey",
      uk: "Туреччина",
      es: "Turquía",
      fr: "Turquie",
      de: "Türkei",
      zh: "土耳其",
      hi: "तुर्की",
      ar: "تركيا",
      pt: "Turquia",
      ru: "Турция",
      ja: "トルコ",
    },
  },
  {
    code: "TM",
    name: {
      en: "Turkmenistan",
      uk: "Туркменістан",
      es: "Turkmenistán",
      fr: "Turkménistan",
      de: "Turkmenistan",
      zh: "土库曼斯坦",
      hi: "तुर्कमेनिस्तान",
      ar: "تركمانستان",
      pt: "Turcomenistão",
      ru: "Туркменистан",
      ja: "トルクメニスタン",
    },
  },
  {
    code: "TV",
    name: {
      en: "Tuvalu",
      uk: "Тувалу",
      es: "Tuvalu",
      fr: "Tuvalu",
      de: "Tuvalu",
      zh: "图瓦卢",
      hi: "तुवालु",
      ar: "توفالو",
      pt: "Tuvalu",
      ru: "Тувалу",
      ja: "ツバル",
    },
  },
  {
    code: "UG",
    name: {
      en: "Uganda",
      uk: "Уганда",
      es: "Uganda",
      fr: "Ouganda",
      de: "Uganda",
      zh: "乌干达",
      hi: "युगांडा",
      ar: "أوغندا",
      pt: "Uganda",
      ru: "Уганда",
      ja: "ウガンダ",
    },
  },
  {
    code: "UA",
    name: {
      en: "Ukraine",
      uk: "Україна",
      es: "Ucrania",
      fr: "Ukraine",
      de: "Ukraine",
      zh: "乌克兰",
      hi: "यूक्रेन",
      ar: "أوكرانيا",
      pt: "Ucrânia",
      ru: "Украина",
      ja: "ウクライナ",
    },
  },
  {
    code: "AE",
    name: {
      en: "United Arab Emirates",
      uk: "Об'єднані Арабські Емірати",
      es: "Emiratos Árabes Unidos",
      fr: "Émirats arabes unis",
      de: "Vereinigte Arabische Emirate",
      zh: "阿拉伯联合酋长国",
      hi: "संयुक्त अरब अमीरात",
      ar: "الإمارات العربية المتحدة",
      pt: "Emirados Árabes Unidos",
      ru: "ОАЭ",
      ja: "アラブ首長国連邦",
    },
  },
  {
    code: "GB",
    name: {
      en: "United Kingdom",
      uk: "Великобританія",
      es: "Reino Unido",
      fr: "Royaume-Uni",
      de: "Vereinigtes Königreich",
      zh: "英国",
      hi: "यूनाइटेड किंगडम",
      ar: "المملكة المتحدة",
      pt: "Reino Unido",
      ru: "Великобритания",
      ja: "イギリス",
    },
  },
  {
    code: "US",
    name: {
      en: "United States",
      uk: "Сполучені Штати",
      es: "Estados Unidos",
      fr: "États-Unis",
      de: "Vereinigte Staaten",
      zh: "美国",
      hi: "संयुक्त राज्य अमेरिका",
      ar: "الولايات المتحدة",
      pt: "Estados Unidos",
      ru: "США",
      ja: "アメリカ",
    },
  },
  {
    code: "UY",
    name: {
      en: "Uruguay",
      uk: "Уругвай",
      es: "Uruguay",
      fr: "Uruguay",
      de: "Uruguay",
      zh: "乌拉圭",
      hi: "उरुग्वे",
      ar: "أوروغواي",
      pt: "Uruguai",
      ru: "Уругвай",
      ja: "ウルグアイ",
    },
  },
  {
    code: "UZ",
    name: {
      en: "Uzbekistan",
      uk: "Узбекистан",
      es: "Uzbekistán",
      fr: "Ouzbékistan",
      de: "Usbekistan",
      zh: "乌兹别克斯坦",
      hi: "उज़्बेकिस्तान",
      ar: "أوزبكستان",
      pt: "Uzbequistão",
      ru: "Узбекистан",
      ja: "ウズベキスタン",
    },
  },
  {
    code: "VU",
    name: {
      en: "Vanuatu",
      uk: "Вануату",
      es: "Vanuatu",
      fr: "Vanuatu",
      de: "Vanuatu",
      zh: "瓦努阿图",
      hi: "वनुआतु",
      ar: "فانواتو",
      pt: "Vanuatu",
      ru: "Вануату",
      ja: "バヌアツ",
    },
  },
  {
    code: "VE",
    name: {
      en: "Venezuela",
      uk: "Венесуела",
      es: "Venezuela",
      fr: "Venezuela",
      de: "Venezuela",
      zh: "委内瑞拉",
      hi: "वेनेज़ुएला",
      ar: "فنزويلا",
      pt: "Venezuela",
      ru: "Венесуэла",
      ja: "ベネズエラ",
    },
  },
  {
    code: "VN",
    name: {
      en: "Vietnam",
      uk: "В'єтнам",
      es: "Vietnam",
      fr: "Viêt Nam",
      de: "Vietnam",
      zh: "越南",
      hi: "वियतनाम",
      ar: "فيتنام",
      pt: "Vietnã",
      ru: "Вьетнам",
      ja: "ベトナム",
    },
  },
  {
    code: "YE",
    name: {
      en: "Yemen",
      uk: "Ємен",
      es: "Yemen",
      fr: "Yémen",
      de: "Jemen",
      zh: "也门",
      hi: "यमन",
      ar: "اليمن",
      pt: "Iêmen",
      ru: "Йемен",
      ja: "イエメン",
    },
  },
  {
    code: "ZM",
    name: {
      en: "Zambia",
      uk: "Замбія",
      es: "Zambia",
      fr: "Zambie",
      de: "Sambia",
      zh: "赞比亚",
      hi: "ज़ाम्बिया",
      ar: "زامبيا",
      pt: "Zâmbia",
      ru: "Замбия",
      ja: "ザンビア",
    },
  },
  {
    code: "ZW",
    name: {
      en: "Zimbabwe",
      uk: "Зімбабве",
      es: "Zimbabue",
      fr: "Zimbabwe",
      de: "Simbabwe",
      zh: "津巴布韦",
      hi: "जिम्बाब्वे",
      ar: "زيمبابوي",
      pt: "Zimbábue",
      ru: "Зимбабве",
      ja: "ジンバブエ",
    },
  },
];

export default countries;
